### ISSUE TITLE
VS 16.6-16.8 tooling performance

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#10081]
Over the past few releases, we've made some incremental improvements to VS tooling. The biggest of them was rewriting how symbols are found for Find All References and Rename.

The following specific issues were all resolved and carried over from https://github.com/dotnet/fsharp/issues/6866

- [x] #8339 - Optimized find all refs and reduced memory usage in VS
- [x] #8234 - Using ArrayPool for AssocTable
- [x] #8021 - TcSymbolUses - significant memory consumption and allocations
- [x] #6791 - Add cache invalidation policy when a solution changes

Some of the perf adjustments did not have a specific issue associated with them.
