### ISSUE TITLE
meta issue: parser related changes

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#11481]
This is a (for now) blank issue, with intent of assembling list of issues/enhancement requests around the F# parser. The idea is to have a hub to ease onboarding of contributions to the parser by the community or main stake holders maintaining the language, in similar fashion we have issue #1103.

I'll just put the categories I know of, for now.

---------
# error recovery in the parser

those issues are about enabling damage mitigation in case of syntax error, for the tooling to recover and remain usable.

See the "thriller" which is a good intro of current state of things: https://youtu.be/3Zr0HNVcooU?t=4977

* [ ] #11468 broken DU decl (missing `of`) breaks the whole file
* [ ] #10872 recovery for unfinished `match`

# adjustments / inconsistencies in the AST

those issues are about making the AST more consistent, and reducing needs of adhoc hacks in tooling to work around some of the historical choices made for the AST representation out of the parser.

* [ ] #11474 Correct range of SynTypeDefnSig. 
* [ ] #11477 Add KeywordString to SynConst type (preserving __LITERALS__)

# error messages to enhance that incur dealing with the parser tokens

those issues are meant as a subset of #1103 when a particular issue has been investigated and identified as "best fixed through change in the parsing".

--------

@tihan, @auduchinok , @nojaf & others, if you have tickets you want me to list here, you can ping me on the slack or elsewhere and I'll bring them up / classify. If there are other categories to add, please let me know.

Hope this serves as useful as our model issue handled by @isaacabraham 🙂

**Comment by baronfel** [comment]
@smoothdeveloper the note you have for #11487 can be checked off now :)
