### ISSUE TITLE
Tracking issues for code examples for all members, functions and types in FSharp.Core

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#12124]
Related to https://twitter.com/dsymetweets/status/1435311963781861376

This is a tracking issue for adding code examples for all functions, members and types in FSharp.Core.  
* An example of the kind of thing that needs to be added is here: https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Core/option.fsi#L136-L142. 
* Once integrated, your examples will appear in the F# core library docs here https://fsharp.github.io/fsharp-core-docs/

Modules and types to do:

* [ ] FSharp.Core.Operators
* [ ] FSharp.Core.String
* [ ] FSharp.Core.Printf
* [x] FSharp.Collections.Option
* [ ] FSharp.Collections.List
* [ ] FSharp.Collections.Array
* [ ] FSharp.Collections.Seq
* [ ] FSharp.Collections.Map
* [ ] FSharp.Collections.Set
* [ ] FSharp.Collections.Array2D
* [ ] FSharp.Collections.Array3D
* [ ] FSharp.Collections.Array4D
* [ ] FSharp.Collections.HashIdentity
* [ ] FSharp.Collections.ComparisonIdentity
* [ ] FSharp.Control.Async
* [ ] FSharp.Control.Async.CommonExtensions
* [ ] FSharp.Control.Async.WebExtensions
* [ ] FSharp.Control.Event
* [ ] FSharp.Control.Observable
* [ ] FSharp.Control.Task
* [ ] FSharp.Quotations
* [ ] FSharp.Quotations.BasicPatterns
* [ ] FSharp.Quotations.DerivedPatterns
* [ ] FSharp.Reflection.FSharpType
* [ ] FSharp.Reflection.FSharpValue

**Comment by baronfel** [comment]
One thing I would really encourage people to do is add a `lang=fsharp` attribute to your `code` example XML tags. It's not strictly speaking to-spec (IMO the .Net XML Documentation spec is fairly lacking here), but it is used in several places (like FSharp.Formatting and FsAutoComplete) to provide the consumer with language-aware syntax highlighting.  Stealing from @nhirschey's examples a bit:

* blit:
```fsharp
///<example>
/// The following sample shows how to copy the first two elements of an array to the 
/// second and third positions of another array:
///
///<code lang="fsharp">
///     let source = [| 1; 2; 3 |]
///     let sourceIndex = 0
///     let target = [| 0; 0; 0 |]
///     let targetIndex = 1
///     let count = 2
///     Array.blit source sourceIndex target targetIndex count 
///     target // evaluates to [| 0; 1; 2 |]
///</code>
///</example>
```

**Comment by dsyme** [comment]
@baronfel  thank you, yes! Is it used consistently in Fsharp.core today? If not please submit a pr to do that?

We should also mention that here

https://github.com/fsharp/fslang-design/blob/main/tooling/FST-1031-xmldoc-extensions.md

**Comment by dsyme** [comment]
@nhirschey thank you so much for kicking this off - the examples for Array can be reused for list and seq of course 

1. multiline samples are definitely needed. Separate them out and take as much space as you need. For complex functions more discursive text may be needed.

2. Regarding equivalences - I think not.

3. Yes but I'm not sure what it should be. I expect 80. We will move to one-function-per-page docs for fsharp.core fsdocs eventually when much more space will be available so don't restrict up 60

**Comment by MecuSorin** [comment]
I will use those as an exercise for my son in his attempt to learn F#. I am very serious. What he is not able/experienced enough, I will do them myself.

**Comment by dsyme** [comment]
@JYCabello The same examples should generally be used for Seq, Array, List (with minor adjustment) - so since @nhirschey is starting at the top of Array I recommend you start at the bottom of Seq, alphabetically?

**Comment by JYCabello** [comment]
I will do. Starting tomorrow.

**Comment by MecuStefan** [comment]
`String` is done, working on the `List` at the moment

**Comment by JYCabello** [comment]
Got to ask: The examples go between the docs for the params and the return type for any particular reason?

**Comment by dsyme** [comment]
> Got to ask: The examples go between the docs for the params and the return type for any particular reason?

No reason - they should be come after I agree.  Please feel free to submit a PR doing a re-ordering

**Comment by JYCabello** [comment]
Great, will do after that. I just noticed that you specifically mentioned to start on the bottom and I started on the top. Sorry about that. I'll make a PR in a bit to have some progress in and to get some feedback.

**Comment by MaxWilson** [comment]
I will take Set.

**Comment by JustinWick** [comment]
I'm going to give FSharp.Control.Async a stab, should be fun. Probably won't be able to get to the extensions, though.

**Comment by dsyme** [comment]
Thank you Max! Thank you Justin!

**Comment by JustinWick** [comment]
Alright, I'm up to 13 examples for Async, I'm expecting to create a PR by Thursday. Do I just file the PR and then have peer review there?

**Comment by dsyme** [comment]
>Alright, I'm up to 13 examples for Async, I'm expecting to create a PR by Thursday. Do I just file the PR and then have peer review there?

Fantastic!  Yes, that's right

**Comment by sgoguen** [comment]
I will take FSharp.Core.Operators

**Comment by dsyme** [comment]
@sgoguen Great!

**Comment by dsyme** [comment]
https://github.com/dotnet/fsharp/pull/12161 contains work to add `<example-tbd>` to all the places we need examples, except in Operators.

**Comment by JustinWick** [comment]
> https://github.com/dotnet/fsharp/pull/12161 contains work to add `<example-tbd>` to all the places we need examples, except in Operators.
> 
> @justinwick There may be a few minor merge conflicts if you've done more work, e.g. in Async - they should be easy to resolve - perhaps before merging first reduce the indenting in  async.fsi to match the change in that PR, then the conflicts will be easy to resolve.
> 

I am just about done with examples but I forgot to transfer them to my laptop before leaving for a trip. I'll be back Tuesday and can merge them into the PR Wednesday, is that going to cause any issues?

**Comment by dsyme** [comment]
> I am just about done with examples but I forgot to transfer them to my laptop before leaving for a trip. I'll be back Tuesday and can merge them into the PR Wednesday, is that going to cause any issues?

@JustinWick It'll be fine, we won't start on Async - thanks!

**Comment by JYCabello** [comment]
> #12161 contains work to add `<example-tbd>` to all the places we need examples, except in Operators.
> 
> @JustinWick There may be a few minor merge conflicts if you've done more work, e.g. in Async - they should be easy to resolve - perhaps before merging first reduce the indenting in async.fsi to match the change in that PR, then the conflicts will be easy to resolve.

Yeah, I hit a lot of merge conflicts and each one of them was simple.

**Comment by sgoguen** [comment]
I've done a number of examples in FSharp.Core.Operators but I'm slow on getting them all finished.

Should I push a PR for what I have so others can add?

https://github.com/sgoguen/fsharp/tree/dev/fsharp-core-examples

**Comment by dsyme** [comment]
Yes please! those look great!

**Comment by JYCabello** [comment]
Haven't forgotten about this, will get back on it ending this week.

**Comment by dsyme** [comment]
With this PR we are at: 

* 309 examples completed (some multiple per item)
* 766 `example-tbd` remaining in FSharp.Core

**Comment by dsyme** [comment]
@JustinWick Do you have the examples for Async in progress? Thanks.  I'd love to get those in

**Comment by dsyme** [comment]
HashIdentity and ComparisonIdentity done in https://github.com/dotnet/fsharp/pull/12223

**Comment by dsyme** [comment]
`Map` and much of `Operators` have been compelted in #12228 and #12233. After these PRs the status is:

* 777 completed examples
* 468 undocumented `<example-tbd>`

To get a feel for what a difference this makes, please check out completed pages linked in the tracking list at the top of the PR

**Comment by dsyme** [comment]
@JustinWick any progress on the async samples? It would be great to get this whole work item closed out, we've made such good progress in F# 6

**Comment by JustinWick** [comment]
Sorry for dropping off the face of the earth, work exploded.

And yes, I have the day off finally so I can put my PR together! Will have
a candidate in by end of the weekend Boston time.

**Comment by dsyme** [comment]
@JustinWick Great! Anything you have would be good, so we can aboid overlap

**Comment by JustinWick** [comment]
@dsyme: Thank you very much for your patience, I bit off a bit much for my first contribution.

I've got all my ducks in a row here and filed my PR #12477. It's not complete, as there were a few functions that were not there when I started on F# 5, are legacy functions, or for which I wasn't immediately able to think of an example. Still, I've added 22 examples, which should be a solid start.

**Comment by leolorenzoluis** [comment]
@dsyme Please review my PR https://github.com/dotnet/fsharp/pull/12644 when you get a chance :)

**Comment by dsyme** [comment]
Great to see more progress on this!

**Comment by dsyme** [comment]
Great to see Observable be completed!  Not that many more to go :)
