### ISSUE TITLE
November/December 2021 work list

### ISSUE THREAD

**Issue by TIHan** [dotnet/fsharp#12331]
- [x] @KevinRansom #12158
- [ ] @KevinRansom is going to look at the current state of the VS prototype for CodeLensAnnotations (see below)
- [ ] @dsyme with community #12124 
- [ ] @dsyme https://github.com/dotnet/fsharp/issues/12071
- [x] @vzarytovskii https://github.com/dotnet/fsharp/issues/12083
- [x] @vzarytovskii @TIHan Validate tail-call optimizations #12196 
- [x] @vzarytovskii @TIHan Add CI job for deterministic builds #12335
- [x] @TIHan Split reference assembly PR into two separate PRs https://github.com/dotnet/fsharp/pull/11521
- [x] @KevinRansom https://github.com/dotnet/fsharp/issues/12467
