### ISSUE TITLE
Tracking issue for expression evaluator and debugger improvements

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#12812]
# Description
This is a list of the [expression evaluator](https://github.com/dotnet/roslyn/tree/main/src/ExpressionEvaluator) and debugging experience improvements we want/plan to do.

> Note, that right now, a standard expression evaluator (link above) is used, so some F#-specific features are not working.
> More info about EE extensibility [here](https://github.com/Microsoft/ConcordExtensibilitySamples/wiki/CLR-Expression-Evaluators)
- [ ] [Support F# expressions in debugger eval](https://github.com/dotnet/fsharp/issues/2544).
- [ ] Have a separate expression evaluator for F#, based on C# one, hidden under a preview feature flag in VS
- [ ] Support F# expressions in watch window.
- [ ] Support F# expressions in immediate window.
- [ ] [Support for "Autos" window for F#](https://github.com/dotnet/fsharp/issues/4271)
- [ ] [Emit open namespaces, modules, and types](https://github.com/dotnet/fsharp/issues/1003).
- [ ] [Show uncaptured locals in closures](https://github.com/dotnet/fsharp/issues/11262).
- [ ] [Show locals when debugging](https://github.com/dotnet/fsharp/issues/12409).
- [ ] [Capture type-level let binds](https://github.com/dotnet/fsharp/issues/3759)
- [ ] [Properly show unit arguments in locals](https://github.com/dotnet/fsharp/issues/12408).
- [ ] [Properly show variables with special names](https://github.com/dotnet/fsharp/issues/12772).
- [ ] [Emit compile-time values in PDB](https://github.com/dotnet/fsharp/issues/12003).
- [ ] [Emit `StateMachineMethod` in PDB](https://github.com/dotnet/fsharp/issues/12000)
- [ ] [Emit `DynamicLocalVariables` in PDB](https://github.com/dotnet/fsharp/issues/12001)
- [ ] [Emit `CompilationOptions` in PDB](https://github.com/dotnet/fsharp/issues/12002)
- [ ] [Emit `ExcludeFromCodeCoverage` attribute for generated methids](https://github.com/dotnet/fsharp/issues/12402).

**Comment by dsyme** [comment]
We could add issues for debugging improvements that require adding more tables, consumed by an F# debug engine.  For example

* Emit a table containing a mapping that allows a "compiler inlined" section of one method to be associated with the actual originating code which has been inlined, including showing multiple stack frames and using different locals mappings.  

* Emit tables that improve the debug experience for computation expressions.  I'd need to formulate exact proposals.

* Probably a bunch of other things too
