### ISSUE TITLE
`Tracking` C#<->F# interop

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#14015]
Tracking issue for .NET/C# interop:
- [ ] Scoped refs.
- [ ] C# & F# Records interop - [suggestion](https://github.com/fsharp/fslang-suggestions/issues/1138)
- [ ] `CallerArgumentExpressionAttribute` support - [suggestion](https://github.com/fsharp/fslang-suggestions/issues/966)
- [ ] `DefaultInterpolatedStringHandler` support - [suggestion](https://github.com/fsharp/fslang-suggestions/issues/1108)
