### ISSUE TITLE
Tracking issue - improve FSI debugging

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#17306]
**FSharp Interactive debugging was never good, and it has got much worse.**

This is a tracking bug to try to collect the activities that may improve it.
- [ ] Debugging can't find source.  The generated multi-emit symbol files do not contain source.
- [ ] Performance:  Symbol files are always generated even when not debugging
- [ ] Watch variables do not work: #14572
- [ ] Local variables do not work: related to #14572
- [ ] There should be a separate set of configurable options when debugging, such optimization off, tailcall off.
- [ ] Debugging should not require disable "Just my code":  #17148, 
- [ ] While using the VisualFSharp solution it should be easier to debug a local coreclr build

**Comment by rgbav** [comment]
pleeeaaaase someone implement proper script debugging. This is a very important feature to convince others to use F# for scripting and to be more enjoyable for beginners.
