### ISSUE TITLE
`Epic` F# LSP Work

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#17865]
- [ ] Publish and discuss LSP package plan and architecture (https://github.com/dotnet/fsharp/issues/16402)
- [ ] https://github.com/dotnet/fsharp/issues/16494
- [ ] https://github.com/dotnet/fsharp/issues/16495
- [ ] https://github.com/dotnet/fsharp/issues/16641
