### ISSUE TITLE
VS 2019 16.1 tooling performance

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#6265]
This is an overarching issue that we're using to track F# tooling performance in VS. I expect these to positively impact other F# editors. Much of this work is actually in the compiler, as some things that are fine in a command-line scenario end up costing us dearly in a tooling scenario.

These are all filed based on data gathered from ETL traces with a solution loaded into Visual Studio, _or_ are related to an issue where data was gathered in this way and determined to also be relevant. other issues labeled `Tenet-Performance` that are not listed here are not necessarily gathered in this way.

- [x] #6390 Excessive creation of ILModuleReaders (for more than necessary for solution under measurement)
- [x] #6409 Remove potential leaks when type providers are misauthored
- [x] #6403 ILVersionInfo accounts for 20MB in OOMed VS session
- [x] #5929 - Type providers get created hundreds of times causing large LOH allocations and UI delays inside VS

**Comment by cartermp** [comment]
#6409 is now completed.

**Comment by cartermp** [comment]
#6390 also addresses a problem where significantly more `ILModuleReaders` were created to read metadata in a solution under test (cc @blumu as this was measured with Springfield.sln)

**Comment by cartermp** [comment]
Closing this out as the log of 16.1 perf improvements.
