### ISSUE TITLE
Checklist for transfer to dotnet/fsharp

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#6549]
- [x] Send `dnfadmin` permissions to be an admin to the repo
- [x] Await `dnfadmin` acceptance
- [x] Write [RFC](https://github.com/fsharp/fslang-design/blob/master/tooling/FST-1007-move-visualfsharp-repo.md)
- [x] Rename repository to `fsharp`
- [x] Perform [organization transfer](https://help.github.com/en/articles/transferring-a-repository#transferring-a-repository-owned-by-your-organization)
- [x] Create new build definitions
- [x] Update auto-merge definitions

**Comment by forki** [comment]
Wow. +💯

**Comment by cartermp** [comment]
Doneski.
