### ISSUE TITLE
Checklist for publishing FCS from this repository

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#6874]
Checklist for: https://github.com/fsharp/fslang-design/blob/master/tooling/FST-1008-publish-fcs-from-upstream-repo.md

- [ ] Issue and PR triage and transfer
- [ ] Reverse-integrate remaining FSharp.Compiler.Service bits into `/fcs`
- [ ] Ensure the FCS bits are signed as a part of our build
- [ ] Set up a build definition for the FCS build to also output a `.nupkg` in CI artifacts
- [ ] Set up post-build step to sign and upload the `.nupkg` into MyGet
- [ ] Ensure that it's still simple to build an unsigned `.nupkg` for yourself out of this repo
- [ ] Establish package ownership for FCS in NuGet as specified in the RFC

@brettfo I don't 100% remember what we need to do to ensure the FCS solution can be a part of our signed build. Could you reply with details on that?

**Comment by baronfel** [comment]
I should be able to send a reverse-integration MR this week after https://github.com/fsharp/FSharp.Compiler.Service/pull/903 is published. That'll result in the diffs between the repos being relatively small, should make the overall task easier.

**Comment by cartermp** [comment]
This can be closed and superseded by the work done
