### ISSUE TITLE
VS 16.5 Tooling Performance

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#8255]
This is an overarching issue that we're using to track F# tooling performance in VS up to VS 16.5. I expect these to positively impact other F# editors. Much of this work is actually in the compiler, as some things that are fine in a command-line scenario end up costing us dearly in a tooling scenario.

These are all filed based on data gathered from ETL traces with a solution loaded into Visual Studio, or are related to an issue where data was gathered in this way and determined to also be relevant. other issues labeled Tenet-Performance that are not listed here are not necessarily gathered in this way.

- [x] #7971- LOH byte array allocations in the IDE from metadata
- [x] #7973 - Char array and String LOH allocations for UnicodeFileAsLexbuf 
- [x] #6863 - Remove reference counting from IncrementalBuilder and rely on the GC
- [x] #7983 - TcSymbolUseData array LOH allocations
- [x] #8058-  Use TokenTup object pool to reduce allocations in LexFilter
- [x] #8175 - Use for..in..do instead of List.iter to prevent function allocations (~2.5% of sample allocations come from function objects)

**Comment by cartermp** [comment]
All other tracking issues: https://github.com/dotnet/fsharp/issues/6866
