### ISSUE TITLE
3-week rollup plan and checklist (April-May 2020)

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#8961]
## Prelude

We're going to try a change for our planning and work tracking by moving things to GitHub. We have a meeting every 3 weeks and go through the things we'd like to focus on, and we'd like to share that on GitHub. The goal is to give more visibility into what we're intending to accomplish for a given time period and track those things over time if they eclipse a single sprint's worth of work.

Additionally, the COVID-19 outbreak has affected the way we work and over overall output: https://github.com/dotnet/fsharp/issues/8879 - what we track here represents our intentions, but not necessarily our commitments.

## Overarching priorities

This list represents our overall priorities that go beyond a particular sprint. The intention isn't to track items that we can call "complete". Instead, they represent what we view as generally important to focus on.

* Fix any high-priority bugs or regressions
* Release a great F# 5 alongside .NET 5
* Continue to invest in the performance and stability of Visual Studio tooling for F#
* Ensure there is a great experience for F# in .NET Interactive and Jupyter Notebooks
* Support the F# OSS community by reviewing their contributions and helping them along
* Improve our infrastructure

## Focus items for this 3 week period

This set of lists represents what we're working on now, and hope to accomplish. Nothing here is guaranteed to be accomplished by a given date, since we will only merge and ship changes when they have an appropriate high level of quality. Sometimes things are easier than they seem, and sometimes they are harder.

### F# 5

- [x] Thoroughly review Witness Passing w.r.t Trait Constraints (#6810 ) - @TIHan 
- [x] Bring up Extension Members Visible to Trait Constraints for review (#6805 ) - @dsyme 
- [ ] Bring up Tasks and Resumable State Machines for review (#6811) - @dsyme 
- [x] Bring up String Interpolation for review (#8907) - @dsyme 

### Core F#

- [x] Perf improvements for VS tooling w.r.t. Find References - @TIHan 
- [x] Bug fix for VS tooling memory leak when switching solutions - @TIHan
- [x] Update legacy templates to reference latest FSharp.Core (#8950) - @KevinRansom 
- [x] Address regressions related to Type Providers (#8913, #8881, #8743) - @KevinRansom 
- [ ] Investigate a fix for DependencyManager/AssemblyLoadContext to unlock .NET Standard 2.0 FCS - @KevinRansom 
- [x] Resolve NGEN issues in DependencyManager (#8942) - @brettfo 
- [x] Modernize FsLexYacc to .NET Core and .NET Standard (https://github.com/fsprojects/FsLexYacc/issues/78) - @cartermp 
- [ ] Modernize Type Provider SDK to be .NET Standard only (https://github.com/fsprojects/FSharp.TypeProviders.SDK/pull/339) - @cartermp 

### F# support in .NET Interactive and Jupyter Notebooks scenarios

- [ ] Draft RFC for `#!nuget` for Jupyter notebooks - @KevinRansom and @cartermp 
- [ ] Dependency remoting support for Spark .NET - @KevinRansom 
- [ ] Input / password support for .NET Kernel - @dsyme 
- [x] .NET Interactive language services API plumbing - @brettfo 
- [x] Variable/value sharing between C# and F# in Jupyter ([PR](https://github.com/dotnet/interactive/pull/345)) - @jonsequitur 
- [x] FSI API for getting values/variables from a script session (#9068) - @TIHan 

### Infrastructure

- [x] Use NGEN in our legacy fsharpqa suite in CI - @KevinRansom 

## Rough prioritized backlog

This list of items represents things we are very much planning on completing. However, they are not planned for this sprint specifically. If we complete items above or are blocked on them, we intend on focusing on these issues. This list is not exhaustive.

- [ ] Support for `#r "project"` - @cartermp, @KevinRansom, community
- [ ] Editor performance with `#r "nuget"` - @KevinRansom
- [ ] Complete design changes for `nameof` - @TIHan 
- [ ] Complete design changes for Open Static Classes - @TIHan 
- [ ] FSharp.Core is .NET Standard 2.0 only - @KevinRansom 
- [ ] FSharp.Compiler.Service is .NET Standard 2.0 only (incorporate @baronfel's work) - @cartermp, @KevinRansom 
- [ ] Publish FSharp.Compiler.Service from this repository - @KevinRansom, @cartermp, community
- [ ] Remove the desktop compiler from our build, producing on a CoreCLR-based compiler and FSI - @KevinRansom 
- [ ] Add support for .NET Interactive extensibility in XPlot - @cartermp
