### ISSUE TITLE
3-week rollup plan and checklist (May 2020)

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#9147]
## Overarching priorities

This list represents our overall priorities that go beyond a particular sprint. The intention isn't to track items that we can call "complete". Instead, they represent what we view as generally important to focus on.

* Fix any high-priority bugs or regressions
* Release a great F# 5 alongside .NET 5
* Continue to invest in the performance and stability of Visual Studio tooling for F#
* Ensure there is a great experience for F# in .NET Interactive and Jupyter Notebooks
* Support the F# OSS community by reviewing their contributions and helping them along
* Improve our infrastructure

## Focus items for this 3 week period

This set of lists represents what we're working on now, and hope to accomplish. Nothing here is guaranteed to be accomplished by a given date, since we will only merge and ship changes when they have an appropriate high level of quality. Sometimes things are easier than they seem, and sometimes they are harder.

Previous period: https://github.com/dotnet/fsharp/issues/8961

### F# 5

- [ ] Complete design changes for `nameof` - @TIHan
- [x] Complete Witness Passing feedback (#6810 ) - @dsyme 
- [x] Complete Witness Passing review (#6810 ) - @TIHan 
- [ ] Bring up Tasks and Resumable State Machines for review (#6811) - @dsyme 

### Core F#

- [ ] Investigate a fix for DependencyManager/AssemblyLoadContext to unlock .NET Standard 2.0 FCS - @KevinRansom 
- [ ] Modernize Type Provider SDK to be .NET Standard only (https://github.com/fsprojects/FSharp.TypeProviders.SDK/pull/339) - @cartermp 

### F# support in .NET Interactive and Jupyter Notebooks scenarios

- [x] Ability to set values/variables via FSI API - @TIHan
- [x] QuickInfo for VSCode notebooks - @brettfo 
- [ ] Draft RFC for `#!nuget` for Jupyter notebooks - @KevinRansom and @cartermp 
- [x] Dependency remoting support for Spark .NET - @KevinRansom 
- [ ] Input / password support for .NET Kernel - @dsyme 

### Infrastructure

- [x] Identify which part of fsharpQA test suite are easily moveable and which aren't - @KevinRansom 

## Rough prioritized backlog

This list of items represents things we are very much planning on completing. However, they are not planned for this sprint specifically. If we complete items above or are blocked on them, we intend on focusing on these issues. This list is not exhaustive.

- [ ] Support for `#r "project"` - @cartermp, @KevinRansom, community
- [ ] Editor performance with `#r "nuget"` - @KevinRansom 
- [ ] Complete design changes for Open Static Classes - @TIHan 
- [ ] FSharp.Core is .NET Standard 2.0 only - @KevinRansom 
- [ ] FSharp.Compiler.Service is .NET Standard 2.0 only (incorporate @baronfel's work) - @cartermp, @KevinRansom 
- [ ] Publish FSharp.Compiler.Service from this repository - @KevinRansom, @cartermp, community
- [ ] Remove the desktop compiler from our build, producing on a CoreCLR-based compiler and FSI - @KevinRansom 
- [ ] Add support for .NET Interactive extensibility in XPlot - @cartermp

**Comment by cartermp** [comment]
https://github.com/dotnet/fsharp/issues/9265
