### ISSUE TITLE
June(ish) 2020 rollup plan and checklist

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#9411]
## Overarching priorities

This list represents our overall priorities that go beyond a particular sprint. The intention isn't to track items that we can call "complete". Instead, they represent what we view as generally important to focus on.

* Fix any high-priority bugs or regressions
* Release a great F# 5 alongside .NET 5
* Continue to invest in the performance and stability of Visual Studio tooling for F#
* Ensure there is a great experience for F# in .NET Interactive and Jupyter Notebooks
* Support the F# OSS community by reviewing their contributions and helping them along
* Improve our infrastructure

## Focus items for this 3 week(ish) period

This set of lists represents what we're working on now, and hope to accomplish. Nothing here is guaranteed to be accomplished by a given date, since we will only merge and ship changes when they have an appropriate high level of quality. Sometimes things are easier than they seem, and sometimes they are harder.

Previous period: https://github.com/dotnet/fsharp/issues/9147

### F# 5

- [ ] Complete the open type declarations implementation - @TIHan 
- [ ] Complete the `nameof` implementation - @dsyme 
- [x] Review the string interpolation dessign - @dsyme @TIHan @cartermp @jonsequitur 
- [x] Complete the design for `nameof` and `open type decls` - @dsyme @TIHan @cartermp
- [x] Bring "Allow implementing the same interface at different generic instantiations in the same type" up to reviewable state (#2867) - @KevinRansom @dsyme 

### Core F#

- [ ] Investigate a fix for DependencyManager/AssemblyLoadContext to unlock .NET Standard 2.0 FCS (https://github.com/dotnet/fsharp/issues/8766) - @KevinRansom 
- [ ] Modernize Type Provider SDK to be .NET Standard only (https://github.com/fsprojects/FSharp.TypeProviders.SDK/pull/339) - @cartermp 
- [ ] Investigate how to make `#r "nuget:"` not lazy - @KevinRansom 

### F# support in .NET Interactive and Jupyter Notebooks scenarios

- [x] Proxy Kernel implementation - @TIHan 
- [x] Very basic hover text in VSCode notebooks for F# - @brettfo 
- [x] VSCode ipynb conversion - @brettfo 
- [ ] Draft RFC for `#!nuget` for Jupyter notebooks (https://github.com/dotnet/fsharp/issues/9270) - @KevinRansom and @cartermp 

### Infrastructure

- [x] Test modernization plan - @vzarytovskii 
- [x] Test modernization progress - @vzarytovskii 

## Rough prioritized backlog

This list of items represents things we are very much planning on completing. However, they are not planned for this sprint specifically. If we complete items above or are blocked on them, we intend on focusing on these issues. This list is not exhaustive.

- [ ] Complete work for Extensions and Constraints (#6805)- @dsyme 
- [x] Discuss/consider string interpolations for F# 5 - @cartermp, @TIHan, @KevinRansom, @dsyme 
- [ ] Support for `#r "project"` - @cartermp, @KevinRansom, community
- [ ] Editor performance with `#r "nuget"` - @KevinRansom 
- [ ] FSharp.Core is .NET Standard 2.0 only - @KevinRansom 
- [ ] FSharp.Compiler.Service is .NET Standard 2.0 only (incorporate @baronfel's work https://github.com/dotnet/fsharp/pull/7888) - @cartermp, @KevinRansom 
- [ ] Publish FSharp.Compiler.Service from this repository (https://github.com/dotnet/fsharp/issues/9457) - @KevinRansom, @cartermp, community
- [ ] Remove the desktop compiler from our build, producing on a CoreCLR-based compiler and FSI - @KevinRansom 
- [ ] Add support for .NET Interactive extensibility in XPlot - @cartermp

**Comment by realvictorprm** [comment]
Is this still planned for F# 5 too ?
https://github.com/dotnet/fsharp/pull/6811

**Comment by cartermp** [comment]
Not at this time, no. It's an extremely challenging thing to review and integrate safely, especially since it's not just a simple addition of the comprehension itself.

**Comment by cartermp** [comment]
https://github.com/dotnet/fsharp/pull/8722

**Comment by abelbraaksma** [comment]
Perhaps good to add this to the list: https://github.com/dotnet/fsharp/issues/9295. If I understand it correctly, MSBuild failing is an issue with upstream Setup team, but that they need to be informed of the changes in dependencies (or something like that). Listing it here might help, so that we diff the dep list before the next public build.

**Comment by dsyme** [comment]
Closing as June is over
