### ISSUE TITLE
July-August(ish) 2020 rollup plan and checklist

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#9640]
## Overarching priorities until the .NET 5 release

This list represents our overall priorities that go beyond a particular sprint. The intention isn't to track items that we can call "complete". Instead, they represent what we view as generally important to focus on.

* Fix any high-priority bugs or regressions
* Release a great F# 5 alongside .NET 5
* Continue to invest in the performance and stability of Visual Studio tooling for F#
* Ensure there is a great experience for F# in .NET Interactive and Jupyter Notebooks
* Support the F# OSS community by reviewing their contributions and helping them along
* Improve our testing infrastructure
* Improve our infrastructure

## Focus items for this 3 week(ish) period

This set of lists represents what we're working on now, and hope to accomplish. Nothing here is guaranteed to be accomplished by a given date, since we will only merge and ship changes when they have an appropriate high level of quality. Sometimes things are easier than they seem, and sometimes they are harder.

Previous period: https://github.com/dotnet/fsharp/issues/9411

### F# 5

- [x] Complete the open type declarations implementation - @TIHan 
- [x] Complete the `nameof` implementation - @dsyme 
- [x] Address design questions/issues in string interpolation - @dsyme 
- [x] Finish design for unamanged generic constraints - @vzarytovskii 
- [x] FSharp.Core is .NET Standard 2.0 only - @KevinRansom 
- [x]  Remove the preview attribute from non-slicing APIs in FSharp.Core - @KevinRansom 

### Core F#

- [x] Investigate F# .dll loading issues in Visual Studio for low-memory scenarios - @KevinRansom 
- [ ] Investigate/plan a fix for DependencyManager/AssemblyLoadContext to unlock .NET Standard 2.0 FCS (https://github.com/dotnet/fsharp/issues/8766) - @KevinRansom and @auduchinok 
- [ ] Modernize Type Provider SDK to be .NET Standard only (https://github.com/fsprojects/FSharp.TypeProviders.SDK/pull/339) - @cartermp 
- [x] Investigate how to make `#r "nuget:"` not lazy - @KevinRansom 
- [x] Pull in FCS with aims to publish from this repo - @KevinRansom @brettfo 

### F# support in .NET Interactive and Jupyter Notebooks scenarios

- [x] Progress in F# completion in VSCode notebooks
- [ ] Draft RFC for `#!nuget` for .NET Interactive (https://github.com/dotnet/fsharp/issues/9270) - @KevinRansom and @cartermp 

### Infrastructure

- [x] Fluent F# assertions framework for compiler test suite - @vzarytovskii 
- [x] Test modernization progress - @vzarytovskii 

## Rough prioritized backlog

This list of items represents things we are very much planning on completing. However, they are not planned for this sprint specifically. If we complete items above or are blocked on them, we intend on focusing on these issues. This list is not exhaustive.

- [ ] Complete work for Extensions and Constraints (#6805)- @dsyme 
- [ ] Support for `#r "project"` - @cartermp, @KevinRansom, community
- [ ] Editor performance with `#r "nuget"` - @KevinRansom 
- [ ] FSharp.Compiler.Service is .NET Standard 2.0 only (incorporate @baronfel's work https://github.com/dotnet/fsharp/pull/7888) - @cartermp, @KevinRansom 
- [ ] Publish FSharp.Compiler.Service from this repository (https://github.com/dotnet/fsharp/issues/9457) - @KevinRansom, @cartermp, community
- [ ] Remove the desktop compiler from our build, producing on a CoreCLR-based compiler and FSI - @KevinRansom 
- [ ] Add support for .NET Interactive extensibility in XPlot - @cartermp
